### PR TITLE
Add notepad 

### PR DESCRIPTION
**Pull request by kirkins**
Adding a notepad example. Saves text to local storage. Would like to add a save button instead. Maybe I can copy some of your code from the paint app.

### CODE REVIEW

**Comment by 1j01** [comment]
Sorry for not responding until now. I've honestly put it off because, while I'd like to merge this, I have several problems with it and I don't want to ask you to make a bunch of changes.

The main thing is that notepad doesn't need to be a rich text editor. Other than that, the icon pack is unrelated to adding notepad and shouldn't really be part of the same PR. I can only *easily* merge the whole thing at once. Plus for consistency, I'd want capitalization of commit messages and dashes in filenames as opposed to underscores.

**Comment by 1j01** [comment]
I added Notepad in https://github.com/1j01/98/commit/21a021a0704f1f1a860427edc8aedbc9df27eda6 (and further commits), still missing file management and some other features.
I'll probably work on Paint, and then do file handling stuff next.

**Comment by 1j01** [comment]
I have still not done the file handling stuff...

**Comment by kirkins** [comment]
you use to be cool

**Pull request closed without merging**
